### ISSUE TITLE
When running on a Mac that isn't the project owners the Tesseract framework and its headers are not found

### ISSUE THREAD

**Issue by mark5422** [jpwiddy/TesseractOCR_iOS7-Sample#1]
When running on a Mac that isn't the project owners the Tesseract framework and its headers are not found. A compiler error says unable to find the file TesseractOCR.h.

**Comment by jpwiddy** [comment]
If you browse the project on GitHub, the headers and framework are there. You must have pulled it into Xcode wrong.

**Comment by mark5422** [comment]
Admittedly I used the download link vs. pulling it down. Will give that a shot.

**Comment by jpwiddy** [comment]
Yea, let me know! It's using an older version of the Tesseract library (because it's a third party iOS one), so that may give you a little trouble as well.
